import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";

import 'swiper/css';
import Footer from "@/components/mainLayout/footer/Footer";
import Header from "@/components/mainLayout/header/Header";
import QueryProvider from "@/provider/Provider";
import VideoCard from "@/ui/videoCard/VideoCard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ["cyrillic", "latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <QueryProvider>
          <Header />
          {children}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
